### ISSUE TITLE
aws client error (PermanentRedirect)

### ISSUE THREAD

**Issue by b02202050** [VDIGPKU/CBNet_caffe#7]
Hi, I encounter the error when I run `sh train_cascade.sh`:

tere3927@terence-ubuntu:~/code/python/pytorch/object_detection/cbnet$ sh train_cascade.sh 
Found Detectron ops lib: /home/tere3927/.local/lib/python2.7/site-packages/torch/lib/libcaffe2_detectron_ops_gpu.so
[E init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
INFO train_net.py:  95: Called with args:
INFO train_net.py:  96: Namespace(cfg_file='configs/cascade_rcnn_baselines/e2e_mask_cascade_rcnn_dual-X-152-32x8d-FPN-IN5k_1.44x.yaml', multi_gpu_testing=True, opts=['OUTPUT_DIR', 'detectron-output'], skip_test=False)
configs/cascade_rcnn_baselines/e2e_mask_cascade_rcnn_dual-X-152-32x8d-FPN-IN5k_1.44x.yaml
INFO io.py:  67: Downloading remote file https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/25093814/X-152-32x8d-IN5k.pkl to /tmp/detectron-download-cache/ImageNetPretrained/25093814/X-152-32x8d-IN5k.pkl
Traceback (most recent call last):
  File "tools/train_net.py", line 133, in <module>
    main()
  File "tools/train_net.py", line 102, in main
    assert_and_infer_cfg()
  File "/home/tere3927/code/python/pytorch/object_detection/cbnet/detectron/core/config.py", line 1127, in assert_and_infer_cfg
    cache_cfg_urls()
  File "/home/tere3927/code/python/pytorch/object_detection/cbnet/detectron/core/config.py", line 1136, in cache_cfg_urls
    __C.TRAIN.WEIGHTS = cache_url(__C.TRAIN.WEIGHTS, __C.DOWNLOAD_CACHE)
  File "/home/tere3927/code/python/pytorch/object_detection/cbnet/detectron/utils/io.py", line 68, in cache_url
    download_url(url, cache_file_path)
  File "/home/tere3927/code/python/pytorch/object_detection/cbnet/detectron/utils/io.py", line 114, in download_url
    response = urllib2.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 301: Moved Permanently

What might the problem be?

Thanks you.

**Comment by b02202050** [comment]
Sorry,
Same issue with https://github.com/PKUbahuangliuhe/CBNet/issues/2
